db.peliculas.drop()
//Aquí almacenaré todas las películas tengo pendientes o he visto y me han gustado, con sus respectivos datos.
//{ Nombre: "", Director: "", Categoria: "", ActoresEstrella: ["", ""], Valoracion: , Vista: , Edad: , Fecha: new Date() },

db.peliculas.insertMany([
    { Nombre: "Cadena perpetua",
     Director: "Frank Darabont", 
     Categoria: "Drama", 
     ActoresEstrella: ["Morgan Freeman", "Tim Robbins"], 
     Valoracion: 9.3, 
     Vista: true, 
     Edad:13, 
     Fecha: new Date(1995,02,24) },
    
    { Nombre: "El padrino", Director: "Francis Ford Coppola", Categoria: "Crimen", ActoresEstrella: ["Al Pacino", "Marlon Brando"], Valoracion: 9.2, Vista: false, Edad:18, Fecha: new Date(1972,09,21) },
    { Nombre: "El caballero oscuro", Director: "Christopher Nolan", Categoria: "Accion", ActoresEstrella: ["Christian Bale", "Heath Ledger"], Valoracion: 9, Vista: false, Edad: 12, Fecha: new Date(2008,07,14) },
    { Nombre: "12 hombres sin piedad", Director: "Sidney Lumet", Categoria: "Crimen", ActoresEstrella: ["Henry Fonda", "Lee J. Cobb"], Valoracion: 9, Vista: false, Edad: 0, Fecha: new Date(1957,03,11) },
    { Nombre: "La lista de Schindler", Director: "Steven Spielberg", Categoria: "Historia", ActoresEstrella: ["Liam Neeson", "Ralph Fiennes"], Valoracion: 8.9, Vista: false, Edad: 12, Fecha: new Date(1994,02,5) },
    { Nombre: "El señor de los anillos: El retorno del rey", Director: "Peter Jackson", Categoria: "Aventura", ActoresEstrella: ["Elijah Wood", "Viggo Mortensen"], Valoracion: 8.9, Vista: false, Edad: 12, Fecha: new Date(2003,11,18) },
    { Nombre: "Pulp Fiction", Director: "Quentin Tarantino", Categoria: "Crimen", ActoresEstrella: ["John Travolta", "Uma Thurman", "Samuel L. Jackson", "Wifly"], Valoracion: 8.9, Vista: true, Edad: 18, Fecha: new Date(1995,0,14) },
    { Nombre: "El bueno, el feo y el malo", Director: "Sergio Leone", Categoria: "Oeste", ActoresEstrella: ["Clint Eastwood", "Eli Wallach"], Valoracion: 8.8, Vista: false, Edad: 13, Fecha: new Date(1968,07,8) },
    { Nombre: "El señor de los anillos: La comunidad del anillo", Director: "Peter Jackson", Categoria: "Aventura", ActoresEstrella: ["Elijah Wood", "Ian McKellen", "Orlando Bloom"], Valoracion: 8.8, Vista: false, Edad: 12, Fecha: new Date(2001,11,20) },
    { Nombre: "El club de la lucha", Director: "David Fincher", Categoria: "Drama", ActoresEstrella: ["Brad Pitt", "Edward Norton"], Valoracion: 8.8, Vista: true, Edad: 18, Fecha: new Date(1999,10,6) },
    { Nombre: "Forrest Gump", Director: "Robert Zemeckis", Categoria: "Drama", ActoresEstrella: ["Tom Hanks", "Robin Wright"], Valoracion: 8.8, Vista: true, Edad: 0, Fecha: new Date(1994,08,24) },
    { Nombre: "Origen", Director: "Christopher Nolan", Categoria: "Accion", ActoresEstrella: ["Leonardo DiCaprio", "Joseph Gordon-Levitt"], Valoracion: 8.8, Vista: false, Edad: 12, Fecha: new Date(2010,07,7) },
    { Nombre: "El señor de los anillos: Las dos torres", Director: "Peter Jackson", Categoria: "Aventura", ActoresEstrella: ["Elijah Wood", "Ian McKellen", "Viggo Mortensen"], Valoracion: 8.7, Vista: false, Edad: 12, Fecha: new Date(2002,11,19) },
    { Nombre: "El imperio contraataca", Director: "Irvin Kershner", Categoria: "Accion", ActoresEstrella: ["Mark Hamill", "Harrison Ford"], Valoracion: 8.7, Vista: false, Edad: 0, Fecha: new Date(1980,09,4) },
    { Nombre: "Matrix", Director: "The Wachowski Brother", Categoria: "Accion", ActoresEstrella: ["Keanu Reeves", "Laurence Fishburne"], Valoracion: 8.7, Vista: true, Edad: 18, Fecha: new Date(1999,05,24) },
    { Nombre: "Uno de los nuestros", Director: "Martin Scorsese", Categoria: "Crimen", ActoresEstrella: ["Robert de Niro", "Ray Liotta"], Valoracion: 8.7, Vista: false, Edad: 18, Fecha: new Date(1990,09,20) },
    { Nombre: "Alguien voló sobre el nido del cuco", Director: "Milos Forman", Categoria: "Drama", ActoresEstrella: ["Jack Nicholson", "Louise Fletcher"], Valoracion: 8.7, Vista: false, Edad: 18, Fecha: new Date(1976,09,8) },
    { Nombre: "Los siete samuráis", Director: "Akira Kurosawa", Categoria: "Accion", ActoresEstrella: ["Toshirô Mifune", "Takashi Shimura"] , Valoracion: 8.6, Vista: false, Edad: 0, Fecha: new Date(1954,03,27) },
    { Nombre: "Seven", Director: "David Fincher", Categoria: "Crimen", ActoresEstrella: ["Morgan Freeman", "Brad Pitt", "Kevin Spacey"], Valoracion: 8.6, Vista: false, Edad: 18, Fecha: new Date(1996,0,11) },
    { Nombre: "La vida es bella", Director: "Roberto Benigni", Categoria: "Comedia", ActoresEstrella: ["Roberto Benigni", "Nicoletta Braschi"], Valoracion: 8.6, Vista: false, Edad: 0, Fecha: new Date(1999,01,27) },
    { Nombre: "Ciudad de Dios", Director: "Fernando  Meirelles", Categoria: "Crimen", ActoresEstrella: ["Alexandre Rodrigues", "Leandro Firmino"], Valoracion: 8.6, Vista: false, Edad: 18, Fecha: new Date(2003,0,32) },
    { Nombre: "El silencio de los corderos", Director: "Jonathan Demme", Categoria: "Crimen", ActoresEstrella: ["Joddie Foster", "Anthony Hopkins"], Valoracion: 8.6, Vista: false, Edad: 18, Fecha: new Date(1991,08,7) },
    { Nombre: "¡Qué bello es vivir!", Director: "Frank Capra", Categoria: "Drama", ActoresEstrella: ["James Stewart", "Donna Reed"], Valoracion: 8.6, Vista: false, Edad: 0, Fecha: new Date(1947-0-8) },
    { Nombre: "La guerra de las galaxias", Director: "George Lucas", Categoria: "Aventura", ActoresEstrella: ["Harrison Ford", "Mark Hamill"], Valoracion: 8.6, Vista: false, Edad: 0, Fecha: new Date(1977,10,8) },
    { Nombre: "Salvar al soldado Ryan", Director: "Steven Spielberg", Categoria: "Drama", ActoresEstrella: ["Tom Hanks", "Matt Damon"], Valoracion: 8.6, Vista: false, Edad: 13, Fecha: new Date(1998,08,19) },
    { Nombre: "El viaje de Chihiro", Director: "Hayao Miyazaki", Categoria: "Aventura", ActoresEstrella: ["Daveigh Chase", "Suzanne Pleshette"], Valoracion: 8.6, Vista: true, Edad: 0, Fecha: new Date(2002,09,26) },
    { Nombre: "La milla verde", Director: "Frank Darabont", Categoria: "Drama", ActoresEstrella: ["Tom Hanks", "Michael Clarke Duncan"], Valoracion: 8.6, Vista: true, Edad: 13, Fecha: new Date(2000,01,19) },
    { Nombre: "Interstellas", Director: "Christopher Nolan", Categoria: "Aventura", ActoresEstrella: ["Matthew McConaughey", "Anne Hathaway"], Valoracion: 8.6, Vista: true, Edad: 12, Fecha: new Date(2014,10,8) },
    { Nombre: "Parásitos", Director: "Bong Joon Ho", Categoria: "Comedia", ActoresEstrella: ["Kang-ho Song", "Sun-kyun Lee"], Valoracion: 8.6, Vista: false, Edad: 16, Fecha: new Date(2019,09,26) },
    { Nombre: "El profesional (Léon)", Director: "Luc Besson", Categoria: "Accion", ActoresEstrella: ["Jean Reno", "Gary Oldman"], Valoracion: 8.5, Vista: false, Edad: 18, Fecha: new Date(1995,03,7) },
    { Nombre: "Sospechosos habituales", Director: "Bryan Singer", Categoria: "Crimen", ActoresEstrella: ["Kevin Spacey", "Gabriel Byrne"], Valoracion: 8.5, Vista: false, Edad: 18, Fecha: new Date(1995,08,9) },
    { Nombre: "Harakiri", Director: "Masaki Kobayashi", Categoria: "Accion", ActoresEstrella: ["Tatsuya Nakadai", "Akira Ishihama"], Valoracion: 8.6, Vista: false, Edad: 13, Fecha: new Date(1962,08,17) },
    { Nombre: "El rey león", Director: "Roger Allers", Categoria: "Aventura", ActoresEstrella: ["Matthew Broderick", "Jeremy Irons"], Valoracion: 8.5, Vista: true, Edad: 0, Fecha: new Date(1994,10,9) },
    { Nombre: "Regreso al futuro", Director: "Robert Zemeckis", Categoria: "Aventura", ActoresEstrella: ["Michael J. Fox", "Christopher Lloyd"], Valoracion: 8.5, Vista: true, Edad: 0, Fecha: new Date(1985,11,3) },
    { Nombre: "Titanic", Director: "James Cameron", Categoria: "Drama", ActoresEstrella: ["Leonardo DiCaprio", "Kate Winslet"], Valoracion: 7.8, Vista: true, Edad: 12, Fecha: new Date(1998,0,10) },
    { Nombre: "El lobo de Wall Street", Director: "Martin Scorsese", Categoria: "Crimen", ActoresEstrella: ["Leonardo DiCaprio", "Jonah Hill"], Valoracion: 8.2, Vista: true, Edad: 16, Fecha: new Date(2014,0,18) },
    { Nombre: "1917", Director: "Sam Mendes", Categoria: "Drama", ActoresEstrella: ["Dean-Charles Chapman", "George MacKay"], Valoracion: 8.3, Vista: true, Edad: 12, Fecha: new Date(2020,0,11) },
    { Nombre: "8 millas", Director: "Curtis Hanson", Categoria: "Drama", ActoresEstrella: ["Eminem", "Brittany Murphy"], Valoracion: 7.1, Vista: true, Edad: 18, Fecha: new Date(2002,01,8) },
    { Nombre: "Ted", Director: "Seth MacFarlane", Categoria: "Comedia", ActoresEstrella: ["Mark Wahlberg", "Mila Kunis"], Valoracion: 5.9, Vista: true, Edad: 16, Fecha: new Date(2012,07,11) },
    { Nombre: "Doom", Director: "Andrzej Bartkowiak", Categoria: "Accion", ActoresEstrella: ["Dwayne Johnson", "Karl Urban"], Valoracion: 6.9, Vista: false, Edad: 18, Fecha: new Date(2005,11,31) },
    { Nombre: "La familia Addams", Director: "Barry Sonnenfeld", Categoria: "Comedia", ActoresEstrella: ["Anjelica Huston", "Raul Julia"], Valoracion: 8.5, Vista: true, Edad: 0, Fecha: new Date(1992,03,11) },
    { Nombre: "The Fast and the Furious", Director: "Rob Cohen", Categoria: "Aventura", ActoresEstrella: ["Paul Walker", ""], Valoracion: 8.3, Vista: true, Edad: 12, Fecha: new Date(2001,09,6) },
    { Nombre: "El show de Truman", Director: "Peter Weir", Categoria: "Comedia", ActoresEstrella: ["Jim Carrey", "Vin Diesel"], Valoracion: 8.4, Vista: true, Edad: 0, Fecha: new Date(1998,09,31) },
    { Nombre: "School of rock", Director: "Richard Linklater", Categoria: "Comedia", ActoresEstrella: ["Jack Black", "Mike White"], Valoracion: 8.1, Vista: false, Edad: 0, Fecha: new Date(2004,01,28) },
    { Nombre: "Malditos Bastardos", Director: "Quentin Tarantino", Categoria: "Aventura", ActoresEstrella: ["Brad Pitt", "Diane Kruger"], Valoracion: 8.3, Vista: true, Edad: 18, Fecha: new Date(2009,08,19) },
    { Nombre: "Los odiosos ocho", Director: "Quentin Tarantino", Categoria: "Crimen", ActoresEstrella: ["Samuel L. Jackson", "Kurt Russell"], Valoracion: 7.8, Vista: true, Edad: 18, Fecha: new Date(2016,0,16) },
    { Nombre: "Reservoir Dogs", Director: "Quentin Tarantino", Categoria: "Crimen", ActoresEstrella: ["Harvey Keitel", "Tim Roth"], Valoracion: 8.3, Vista: true, Edad: 18, Fecha: new Date(1992,09,15) },
    { Nombre: "Men in Black", Director: "Barry Sonnenfeld", Categoria: "Accion", ActoresEstrella: ["Will Smith", "Tommy Lee Jones"], Valoracion: 7.3, Vista: true, Edad: 7, Fecha: new Date(1997,06,12) },
    { Nombre: "Soy leyenda", Director: "Francis Lawrence", Categoria: "", ActoresEstrella: ["Will Smith", "Doge"], Valoracion: 7.2, Vista: true, Edad: 13, Fecha: new Date(2007,11,20) },
    { Nombre: "En busca de la felicidad", Director: "Gabriele Muccino", Categoria: "Drama", ActoresEstrella: ["Will Smith", "Jaden Smith"], Valoracion: 8, Vista: true, Edad: 0, Fecha: new Date(2007,01,3) },
    { Nombre: "Náufrago", Director: "Robert Zemeckis", Categoria: "William Broyles Jr.", ActoresEstrella: ["Tom Hanks","Helen Hunt"], Valoracion: 7.8, Vista: false, Edad: 0, Fecha: new Date(2001,0,20) },
]);
    
